name: Testing Page
favicon: null
layout_spectrum: 1
typography_spectrum: 0.78538
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6e8db'
    - '#40291d'
    - '#684839'
    - '#9d6849'
    - '#eca862'
  brandStrength: 0.1875
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
