analytics: {}
color:
  brandColors:
    - '#f6e8db'
    - '#40291d'
    - '#684839'
    - '#9d6849'
    - '#eca862'
  brandStrength: 0.1875
  lightness: 0.4375
  rhythmicContrast: 0.75
  saturation: 0.75
cta: {}
layout_spectrum: 0.143914
name: Testing Page
opengraph: {}
purpose: []
typography_spectrum: 0.78538
