name: Testing Page
favicon: null
layout_spectrum: 0.041076422203332186
typography_spectrum: 0.3579221579711884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#282828'
    - '#dde0e5'
    - '#acafb4'
    - '#83868b'
    - '#5f636c'
  brandStrength: 0.1037342834752053
  lightness: 0.5443463346455246
  saturation: 0.7910430042538792
  rhythmicContrast: 0.6591129384469241
purpose: []
